/*
 * Nordic Game Lab API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NordicGameLabApi);
  }
}(this, function(expect, NordicGameLabApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NordicGameLabApi.DefaultApi();
  });

  describe('(package)', function() {
    describe('DefaultApi', function() {
      describe('v2UserDelete', function() {
        it('should call v2UserDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for v2UserDelete call
          /*
          var opts = {};

          instance.v2UserDelete(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('v2UserGet', function() {
        it('should call v2UserGet successfully', function(done) {
          // TODO: uncomment, update parameter values for v2UserGet call
          /*
          var opts = {};

          instance.v2UserGet(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('v2UserPost', function() {
        it('should call v2UserPost successfully', function(done) {
          // TODO: uncomment, update parameter values for v2UserPost call
          /*
          var opts = {};

          instance.v2UserPost(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
